### ISSUE TITLE
Roads Stylesheet

### ISSUE THREAD

**Issue by Joe-houghton** [OrdnanceSurvey/OS-Vector-Tile-API-Stylesheets#2]
Hi,

Are there any plans to create a Roads style to match the OS Maps API?
[https://osdatahub.os.uk/docs/wmts/technicalSpecification](https://osdatahub.os.uk/docs/wmts/technicalSpecification)

The OS Maps API "Outdoor style" seems to match the OS_VTS_XXX_ESRI.json, the light style has just been added (thanks), typically our PM wants the Roads style to be the default.

Thanks,

Joe

**Comment by charleyglynn** [comment]
Hi @Joe-houghton we will indeed be adding the Road style to this repo soon. Will let you know when it's ready 👍

**Comment by andokai** [comment]
Any update on this?

**Comment by BezBIS** [comment]
We would also be interested in this.

**Comment by egil1978** [comment]
Hey, thanks for showing an interest. We will be working on this shortly and should have something ready soon. Ill post back here once we've uploaded the JSON to the repo. Paul.

**Comment by Joe-houghton** [comment]
Hi @egil1978 Any progress on this? We've got various customers asking for it.

**Comment by egil1978** [comment]
Hi @Joe-houghton apologies this has taken longer than expected. We are just finishing these off now and they should be uploaded this week or next. Ill comment again once they are live.

**Comment by egil1978** [comment]
Hi @Joe-houghton just to keep you updated we are running some final QA and the JSON will be uploaded to the repo next week. Thanks for you patience and apologies this has taken a little longer than promised.

**Comment by egil1978** [comment]
Hi @Joe-houghton just to let you know that the Roads style is now available through the repo for the VTS API.

**Comment by andokai** [comment]
Thanks!

**Comment by Joe-houghton** [comment]
Excellent, thank you!
